Make CONSUL_HTTP_ADDR a required variable

diff --git a/proxy/bin/consul-template-start b/proxy/bin/consul-template-start
--- a/proxy/bin/consul-template-start
+++ b/proxy/bin/consul-template-start
@@ -7,21 +7,14 @@ set -e
 # starting consul-template
 #####
 
-# Decide what address to use for Consul
-# If not explicitly given, we use HOST_IP:8500
-# This will work in Kubernetes with Consul deployed using the official Helm chart
-# and HOST_IP configured via the downward API
+# Require that an address for Consul be provided
 if [ -z "$CONSUL_HTTP_ADDR" ]; then
-    if [ -n "$HOST_IP" ]; then
-        CONSUL_HTTP_ADDR="${HOST_IP}:8500"
-    else
-        echo "CONSUL_HTTP_ADDR or HOST_IP must be set" 1>&2
-        exit 1
-    fi
+    echo "[ERROR] CONSUL_HTTP_ADDR is required" 1>&2
+    exit 1
 fi
 
 if [ -z "$PROXY_BASE_DOMAIN" ]; then
-    echo "[ERROR] Please specify a PROXY_BASE_DOMAIN" 1>&2
+    echo "[ERROR] PROXY_BASE_DOMAIN is required" 1>&2
     exit 1
 fi
 
